{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module PrintPredicateLogic where

-- pretty-printer generated by the BNF converter

import AbsPredicateLogic
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])


instance Print Expression where
  prt i e = case e of
    Term id -> prPrec i 0 (concatD [prt 0 id])
    Predication id expressions -> prPrec i 0 (concatD [prt 0 id, doc (showString "("), prt 0 expressions, doc (showString ")")])
    Conjunction expression1 expression2 -> prPrec i 0 (concatD [doc (showString "("), prt 0 expression1, doc (showString "and"), prt 0 expression2, doc (showString ")")])
    Disjunction expression1 expression2 -> prPrec i 0 (concatD [doc (showString "("), prt 0 expression1, doc (showString "or"), prt 0 expression2, doc (showString ")")])
    Implication expression1 expression2 -> prPrec i 0 (concatD [doc (showString "("), prt 0 expression1, doc (showString "->"), prt 0 expression2, doc (showString ")")])
    Negation expression -> prPrec i 0 (concatD [doc (showString "not"), prt 0 expression])
    Abstraction id expression -> prPrec i 0 (concatD [doc (showString "lambda"), prt 0 id, prt 0 expression])
    Application expression1 expression2 -> prPrec i 0 (concatD [doc (showString "("), prt 0 expression1, doc (showString "@"), prt 0 expression2, doc (showString ")")])
    Quantification quantifier id expression1 expression2 -> prPrec i 0 (concatD [prt 0 quantifier, prt 0 id, doc (showString "["), prt 0 expression1, doc (showString "]"), doc (showString "["), prt 0 expression2, doc (showString "]")])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Quantifier where
  prt i e = case e of
    Exists -> prPrec i 0 (concatD [doc (showString "some")])
    Forall -> prPrec i 0 (concatD [doc (showString "all")])
    Most -> prPrec i 0 (concatD [doc (showString "most")])
    Many -> prPrec i 0 (concatD [doc (showString "many")])
    The -> prPrec i 0 (concatD [doc (showString "the")])
    No -> prPrec i 0 (concatD [doc (showString "no")])
    Few -> prPrec i 0 (concatD [doc (showString "few")])


