module SkelAST where

-- Haskell module generated by the BNF converter

import AbsAST
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident string -> failure x
transExpression :: Expression -> Result
transExpression x = case x of
  Constant ident -> failure x
  List expressions -> failure x

